### ISSUE TITLE
Have users supply their bearer token to the discord bot via DM

### ISSUE THREAD

**Issue by hypervis0r** [kindaconfusion/CanvasBot#7]
To support multiple users, you can store a global dictionary of auth tokens with the Discord user as the key. Users can supply their auth token to the bot via a DM command. Obviously this has security implications, namely the storing of sensitive auth keys, but sacrifices must be made.

**Comment by kindaconfusion** [comment]
no

**Comment by hypervis0r** [comment]
Understandable, have a nice day 🤝
